remote_theme: rundocs/jekyll-rtd-theme

title: Linguagem Potigol
description: Documentação da Linguagem Potigol

meta:
  versao: 1.0.0-RC1

readme_index:
  with_frontmatter: true

translate:
  # shortcodes
  danger: Perigo
  #note:
  tip: Dica
  warning: Atenção
  # 404
  #not_found:
  # copyright
  revision: Versão
  # search
  #searching:
  #search:
  search_docs: Pesquisar documentação
  search_results: Resultado da pesquisa
  #search_results_found: # the "#" in this translate will replaced with results size!
  #search_results_not_found:
  next: Próximo
  previous: Anterior
